kotlin.code.style=official
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# Check these on https://modmuss50.me/fabric.html

# If this properties change. must update fabric.mod.json and README.md file.

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.2

#Fabric api
fabric_version=0.102.1+1.21.1

	loom_version=1.8-SNAPSHOT

	# Mod Properties
	mod_version = 1.0.0
	maven_group = io.github.takusan23
	archives_base_name = ClickManaita-Fabric-1.21.1

	# Kotlin
	kotlin_version=2.0.21
	fabric_kotlin_version=1.12.3+kotlin.2.0.21
